// Generated by Wrangler by running `wrangler types`

interface Env {
  SESSIONS: KVNamespace;
  NODE_VERSION: "22.12.0";
  TURSO_AUTH_TOKEN: string;
  TURSO_URL: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  API_WORKER: Fetcher;
}
