#:schema node_modules/wrangler/config-schema.json
name = "auth"
compatibility_date = "2024-10-22"

compatibility_flags = ["nodejs_compat"]

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "pnpm run build"

workers_dev = true


# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[services]]
binding = "API_WORKER"
service = "api"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#d1-databases
[[d1_databases]]
binding = "DB"
database_name = "acme"
database_id = "fe6b1cc7-1472-4299-b217-64d257a416ba"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "ddb337f2f9c542ed87b3c985b45c5f0d"
