#:schema node_modules/wrangler/config-schema.json
name = "accounts2"
compatibility_date = "2024-12-18"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "22.12.0"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[services]]
binding = "API_WORKER"
service = "api"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "SESSIONS"
id = "ddb337f2f9c542ed87b3c985b45c5f0d"
